### ISSUE TITLE
question about your paper

### ISSUE THREAD

**Issue by zdw-qingdao** [autonomousvision/differentiable_volumetric_rendering#7]
i am confused by the formular (4) and (7),  why there is a addition in the differentiation?

**Comment by m-niemeyer** [comment]
Hi @zdw-qingdao , thanks a lot for your interest in the project.

Regarding your questions, in 4.), We have a sum because our loss function L is a sum of  l1 losses over all sampled pixels u (see 3.)). Then, the gradient of L wrt. the network parameters also becomes a sum over these individual losses on each pixel. 
In 7.), the reason is different. If you differentiate f(p) wrt. the network parameters theta, you have to calculate[ the total derivate](https://en.wikipedia.org/wiki/Total_derivative) as both f as well as p are functions of theta. You have to sum over all partial derivatives, in this case (df / dtheta) as well as (df / dp * dp / dtheta).

**Comment by neon5d** [comment]
I was also very confused especially in (5).
I think eq. (5) looks like this:
<img src="https://render.githubusercontent.com/render/math?math=\frac{d\hat I_u}{d\theta}=\frac{dt_\theta(\hat p)}{d\theta}=\frac{\partial t_\theta(\hat p)}{\partial\theta} %2B \frac{\partial t_\theta(\hat p)}{\partial\hat p}\frac{\partial \hat p}{\partial\theta}">
same way to eq. (7)

**Comment by m-niemeyer** [comment]
In equation 5, the reason for the sum is the same as in 7. 
The predicted RGB color value for pixel u is \hat{I}_u, let's just call it i_pred_u for simplicity here. We get our RGB color value by evaluating the texture field at the predicted 3D surface point t(p), so i_pred_u = t(p). If you now want to calculate the gradient, you have to calculate the [total derivative (see above)](https://en.wikipedia.org/wiki/Total_derivative) because **both**, t as well as p depend on the network parameters theta.

**Comment by zdw-qingdao** [comment]
Thanks you!!!
