### ISSUE TITLE
Configuration files

### ISSUE THREAD

**Issue by neon5d** [autonomousvision/differentiable_volumetric_rendering#8]
Hello, 
Thank you for sharing your great work.
I wonder whether you can share configuration files of ShapeNet and NMR for
single_view_reconstruction/single(multi)_view_supervision and multi_view_reconstruction.

There are some configurations but I am not sure it can be applied for other datasets and supervision.
Thank you,

**Comment by m-niemeyer** [comment]
Hi @neon5d , thanks for your interest! Can you please specify which config you think is missing? Because as you mentioned, there are already respective config files in the folders, e.g. single_view_reconstruction/multi_view_supervision/ours_depth.yaml can be used to train a single-view reconstruction model with depth supervision. Thanks!

**Comment by neon5d** [comment]
It seems "single_view_reconstruction/multi_view_supervision/ours_rgb.yaml" is configured for NMR_Dataset
Can I use the same configuration for ShapeNet after changing "data->path" to derive papers' results?

For "single_view_reconstruction/multi_view_supervision/ours_rgb.yaml" and
"single_view_reconstruction/multi_view_supervision/combined_rgb.yaml" , 
Are these config files can be used for ShapeNet and NMR to derive your paper's experiment?

If I need some changes other than "data->path", can you share your configuration files of ShapeNet and NMR for the paper's experiment?
Thank you

**Comment by m-niemeyer** [comment]
Hi @neon5d , OK, I see what you mean - thanks for the clarification!

First, "ShapeNet" and "NMR" are both the ShapeNet dataset! Only the renderings of the objects are different. We did this because most 3D supervised methods use the Choy et. al. renderings, but most 2D supervised methods use the renderings from Kato et. al. Please see [the "Dataset" paragraph under section 4.1 on page 6 of the paper](http://www.cvlibs.net/publications/Niemeyer2020CVPR.pdf) for more details.  

Hence, for all experiments from the paper, there is a *.yaml config file and a *_pretrained.yaml config file. Hence, you do not need to change the path! I hope this helps, otherwise please let me know!

**Comment by neon5d** [comment]
Thank you for clarification.
